Improve routing to boost clock rate
tensil-ai/tensil pull request #24
Opened 2022-03-17 23:28 UTC by tdb-alcorn

This change

- merges fixed point multiply and add into a single operation called mac, which avoids computing the saturation handling twice
- adds various input buffers to modules as needed to break up long routes

Ultra96v2 now makes timing at 150MHz with a WNS of 0.114ns. The longest routes now pass through the saturation handling in the acc ALUs.

2022-03-17 23:38 UTC, petrohi requested changes
We also need to change golden processor accordingly to have bit accurate results. I will do it in this PR.

2022-03-17 23:38 UTC, petrohi commented on rtl/src/main/scala/tensil/util/package.scala
> +      case _ => x * y
Should also add z here.

2022-03-21 02:42 UTC, petrohi approved these changes

2022-03-22 04:16 UTC, tdb-alcorn commented on sim/test/src/zynq/tcu/AXIWrapperTCUSpec.scala
> +            /*() => xor4(batchSize = 1),
uncomment these again?

2022-03-22 04:56 UTC, petrohi commented on sim/test/src/zynq/tcu/AXIWrapperTCUSpec.scala
> +            /*() => xor4(batchSize = 1),
done

2022-03-23 00:48 UTC, merged